#%RAML 1.0
title: Nitrokey NetHSM API
version: v0
description: All <a href="https://tools.ietf.org/html/rfc4648#section-4">base64url</a> encoded values are Big Endian.
baseUri: https://{hostName}:{hostPort}/api/{version}
baseUriParameters:
  hostName:
    description: Host name or host IP address
  hostPort:
    description: Port of the host
#baseUri: http://mocksvc.mulesoft.com/mocks/bc9055f5-5fb7-4311-98c0-9f4858c5773d/{version}
protocols: HTTPS
mediaType: application/json
securitySchemes:
  basic:
    description: This API supports Basic Authentication.
    type: Basic Authentication
# Maybe describe which user role to use for each operation. See: http://forums.raml.org/t/allow-get-endpoint-to-be-both-secure-and-un-secure/1134/4

types:
  PrivateRsaKey:
    type: object
    properties:
      primeP: string
      primeQ: string
      publicExponent: string
  PublicRsaKey:
    type: object
    properties:
      modulus: string
      publicExponent: string
  KeyImport:
    type: object
    properties:
      purpose: string
      algorithm: string
      privateKey: PrivateRsaKey
  KeyGeneration:
    type: object
    properties:
      purpose: string
      algorithm: string
      length: integer
  KeyImportWithId:
    type: object
    properties:
      purpose: string
      algorithm: string
      privateKey: PrivateRsaKey
      id: string
  KeyGenerationWithId:
    type: object
    properties:
      purpose: string
      algorithm: string
      length: integer
      id: string

/keys:
  description: The keys being stored in the NetHSM
  post:
    description: Import or generate key pair in(to) NetHSM
    securedBy: basic # Administrator
    body:
      application/json:
        type: KeyImport | KeyGeneration
        examples:
          KeyImportWithId:
            purpose: "signing"
            algorithm: "RSA"
            privateKey:
              primeP: "frtz7u89gft89uz"
              primeQ: "FhJQl11CiY0ifRHXeAqFh4rdSl6"
              publicExponent: "w367rg90jhj0asdf98gz"
            id: "myKey1"
          KeyGenerationWithId:
            purpose: "signing"
            algorithm: "RSA"
            length: 2048
            id: "myKey1"
    responses:
      303:
        headers:
          Location:
            example: /api/{version}/e345678uzt5678
      404:
      500:
  get:
    description: Retrieve a list of all key locations.
    securedBy: null
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              location: string

  /{keyLocation}:
    delete:
      description: Deletes key pair
      securedBy: basic # Administrator
      responses:
        200:
        404:
        500:
    put:
      description: Import or generate key pair in(to) NetHSM in a specified location
      securedBy: basic # Administrator
      body:
        application/json:
          type: KeyImport | KeyGeneration
          examples:
            KeyImport:
              purpose: "signing"
              algorithm: "RSA"
              privateKey:
                primeP: "frtz7u89gft89uz"
                primeQ: "FhJQl11CiY0ifRHXeAqFh4rdSl6"
                publicExponent: "w367rg90jhj0asdf98gz"
            KeyGeneration:
                purpose: "signing"
                algorithm: "RSA"
                length: 2048
      responses:
        200:
        404:
        500:
      queryParameters:
        key:
    get:
      description: Retrieve public key
      securedBy: null
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                purpose: string
                algorithm: string
                publicKey: PublicRsaKey
              example:
                purpose: "signing"
                algorithm: "RSA"
                publicKey:
                  modulus: "FhJQl11CiY0ifRHXeAqFh4rdSl6"
                  publicExponent: "FhJQl11CiY0ifRHXeAqFh4rdSl6"

    /public.pem:
      description: Retrieve the public key in PEM format
      get:
        description: Retrieve Public Key
        securedBy: null
        responses:
          200:
            body:
              application/json: # TODO

    /actions/{decryptMode}/decrypt:
      description: Decryption to be performed with the secret key
      uriParameters:
        decryptMode:
          type: string
      post:
        securedBy: basic # User
        body:
          application/json:
            type: object
            properties:
              decrypted: string
            example:
              decrypted: "nhrfotu32409ru0rgert45z54z099u23r03498uhtr"
        responses:
          200:
            body:
              application/json:
                type: object
                properties:
                  status: string
                  data:
                    type: object
                    properties:
                      decrypted: string
                example:
                  status: "ok"
                  data:
                    decrypted: "nhrfotu32409ru0rgert45z54z099u23r03498uhtr"
          404:
          500:

    /actions/{signMode}/sign:
      description: Signature to be performed with the secret key
      uriParameters:
        signMode:
          type: string
      post:
        securedBy: basic # User
        body:
          application/json:
            type: object
            properties:
              message: string
            example:
              message: "nhrfotu32409ru0rgert45z54z099u23r03498uhtr"
        responses:
          200:
            body:
              application/json:
                type: object
                properties:
                  status: string
                  data:
                    type: object
                    properties:
                      signedMessage: string
                example:
                  status: "ok"
                  data:
                    signedMessage: "nhrfotu32409ru0rgert45z54z099u23r03498uhtr"
          404:
          500:

/passwords:
    /admin:
      description: Admin Password is required to authenticate system modifications. It has to be defined before a new device can be used.
      post:
        description: Activate or change the password. Basic Authentication is required for changing but not activating.
        securedBy: [null, basic] # Administrator
        body:
          application/json:
            type: object
            properties:
              newPassword: string
            example:
              newPassword: "nhrfotu32409ru0rgert45z54z099u23r03498uhtr"
        responses:
          200:
          404:
          500:
    /boot:
      description: The Boot Password is required to unlock a freshly booted system. It's optional. Alternatively the User Password is used.
      post:
        description: Activate or change the password. Basic Authentication is required for changing but not activating.
        securedBy: [null, basic] # Boot
        body:
          application/json:
            type: object
            properties:
              newPassword: string
            example:
              newPassword: "nhrfotu32409ru0rgert45z54z099u23r03498uhtr"
        responses:
          200:
          404:
          500:
      delete:
        queryParameters:
        securedBy: basic # Administrator, Boot
        description: Deactivate the password
        responses:
          200:
          404:
          500:
    /user:
      description: User Password is required to execute operations.
      post:
        description: Activate or change the password.
        securedBy: basic # Administrator, User
        body:
          application/json:
            type: object
            properties:
              newPassword: string
            example:
              newPassword: "nhrfotu32409ru0rgert45z54z099u23r03498uhtr"
        responses:
          200:
          404:
          500:
/system:
  /firmware:
    post:
      description: Update the firmware
      securedBy: basic # Administrator
      body:
        application/json:
          #TODO
      responses:
        200:
        500:
    /version:
      description: The version of the installed firmware.
      get:
        description: Retrieve the current firmware version
        securedBy: null
        responses:
          200:
          500:

  /keys:
    description: Keys for the system.
    /firmware/public:
      description: The public key is used to verify signed firmware updates.
      get:
        description: Retrieve public key
        securedBy: basic # Administrator
        body:
          application/json:
        responses:
          200:
            body:
              application/json:
                type: object
                properties:
                  purpose: string
                  algorithm: string
                  publicKey: PublicRsaKey
                example:
                  purpose: "signing"
                  algorithm: "RSA"
                  publicKey:
                    modulus: "FhJQl11CiY0ifRHXeAqFh4rdSl6"
                    publicExponent: "FhJQl11CiY0ifRHXeAqFh4rdSl6"
          404:
          500:
      post:
        description: Import the public key to the NetHSM
        securedBy: basic # Administrator
        body:
          application/json:
            type: object
            properties:
              purpose: string
              algorithm: string
              publicKey: PublicRsaKey
        responses:
          200:
          404:
          500:
      delete:
        description: Delete the public key. No firmware updates will be possible without a public key.
        securedBy: basic # Administrator
        responses:
          200:
          404:
          500:
    /tls:
      description: This key pair and certificate are used for HTTPS/TLS.
      post:
        description: Import or generate a key pair in(to) the NetHSM.
        securedBy: basic # Administrator
        body:
          application/json:
            type: KeyImport | KeyGeneration
            examples:
              KeyImport:
                purpose: "signing"
                algorithm: "RSA"
                privateKey:
                  primeP: "frtz7u89gft89uz"
                  primeQ: "FhJQl11CiY0ifRHXeAqFh4rdSl6"
                  publicExponent: "w367rg90jhj0asdf98gz"
              KeyGeneration:
                  purpose: "signing"
                  algorithm: "RSA"
                  length: 2048
        responses:
          200:
          500:
      /public:
        description: The public key
        get:
          description: Retrieve Public Key
          responses:
            200:
              body:
                application/json:
                  type: object
                  properties:
                    purpose: string
                    algorithm: string
                    publicKey: PublicRsaKey
                  example:
                    purpose: "signing"
                    algorithm: "RSA"
                    publicKey:
                      modulus: "FhJQl11CiY0ifRHXeAqFh4rdSl6"
                      publicExponent: "FhJQl11CiY0ifRHXeAqFh4rdSl6"
            404:
      /certificate:
        description: The X.509 certificate
        get:
        post:
          securedBy: basic # Administrator
          body:
            #TODO
  /lock:
    description: Lock an unlocked system so that no operations are possible anymore until it is unlocked again.
    post:
      securedBy: basic # Administrator, Boot or User
  /name:
    description: The name of the system (e.g. NetHSM)
    get:
  /network:
    /ipv4:
      get:
      post:
        securedBy: basic # Administrator
        body:
          application/json:
            type: object
            properties:
              address: string
              netmask: string
              gateway: string
            example:
              address: "123.456.789.123"
              netmask: "255.255.255.255"
              gateway: "1.1.1.1"
    /ipv6:
      get:
      post:
        securedBy: basic # Administrator
        body:
          application/json:
            type: object
            properties:
              address: string
              netmask: string
              gateway: string
            example:
              address: "2001:0db8:0:f101::1/64"
              netmask: "64"
              gateway: "fe80::1"
  /reboot:
    description: Reboot the system
    post:
      securedBy: basic # Administrator
  /serial:
    description: The system's serial number should be derived from some hardware serials (e.g. CPU ID).
    get:
  /status:
    description: The current system status.
    get:
      securedBy: null
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                status: string
              example:
                status: "ok"

  /shutdown:
    description: Shutdown and poweroff the system.
    post:
      securedBy: basic # Administrator
  /unlock:
    description: Unlock and decrypt all critical data (e.g. keys) after a fresh boot or locking.
    post:
      securedBy: basic # Boot
  /vendor:
    description: The vendor of the system (e.g. Nitrokey)
    get:
